/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountInfo {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "email")]
    pub email: String,
}

impl AccountInfo {
    pub fn new(_id: String, email: String) -> AccountInfo {
        AccountInfo {
            _id,
            email,
        }
    }
}


