/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// AccountStrike : Account Strike



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountStrike {
    /// Strike Id
    #[serde(rename = "_id")]
    pub _id: String,
    /// Id of reported user
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// Attached reason
    #[serde(rename = "reason")]
    pub reason: String,
}

impl AccountStrike {
    /// Account Strike
    pub fn new(_id: String, user_id: String, reason: String) -> AccountStrike {
        AccountStrike {
            _id,
            user_id,
            reason,
        }
    }
}


