/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuthifierError {
    #[serde(rename = "type")]
    pub r#type: RHashType,
    #[serde(rename = "with")]
    pub with: String,
    #[serde(rename = "operation")]
    pub operation: String,
}

impl AuthifierError {
    pub fn new(r#type: RHashType, with: String, operation: String) -> AuthifierError {
        AuthifierError {
            r#type,
            with,
            operation,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "DisallowedMFAMethod")]
    DisallowedMfaMethod,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::DisallowedMfaMethod
    }
}

