/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// BandcampType : Type of remote Bandcamp content

/// Type of remote Bandcamp content
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BandcampType {
    #[serde(rename = "Album")]
    Album,
    #[serde(rename = "Track")]
    Track,

}

impl ToString for BandcampType {
    fn to_string(&self) -> String {
        match self {
            Self::Album => String::from("Album"),
            Self::Track => String::from("Track"),
        }
    }
}

impl Default for BandcampType {
    fn default() -> BandcampType {
        Self::Album
    }
}




