/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// BannedUser : Just enoguh user information to list bans.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BannedUser {
    /// Id of the banned user
    #[serde(rename = "_id")]
    pub _id: String,
    /// Username of the banned user
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "avatar", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Box<crate::models::BannedUserAvatar>>,
}

impl BannedUser {
    /// Just enoguh user information to list bans.
    pub fn new(_id: String, username: String) -> BannedUser {
        BannedUser {
            _id,
            username,
            avatar: None,
        }
    }
}


