/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// Category : Channel category



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Category {
    /// Unique ID for this category
    #[serde(rename = "id")]
    pub id: String,
    /// Title for this category
    #[serde(rename = "title")]
    pub title: String,
    /// Channels in this category
    #[serde(rename = "channels")]
    pub channels: Vec<String>,
}

impl Category {
    /// Channel category
    pub fn new(id: String, title: String, channels: Vec<String>) -> Category {
        Category {
            id,
            title,
            channels,
        }
    }
}


