/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// ChannelOneOf3DefaultPermissions : Default permissions assigned to users in this channel



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChannelOneOf3DefaultPermissions {
    /// Allow bit flags
    #[serde(rename = "a")]
    pub a: i64,
    /// Disallow bit flags
    #[serde(rename = "d")]
    pub d: i64,
}

impl ChannelOneOf3DefaultPermissions {
    /// Default permissions assigned to users in this channel
    pub fn new(a: i64, d: i64) -> ChannelOneOf3DefaultPermissions {
        ChannelOneOf3DefaultPermissions {
            a,
            d,
        }
    }
}


