/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// ChannelCompositeKey : Composite primary key consisting of channel and user id



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChannelCompositeKey {
    /// Channel Id
    #[serde(rename = "channel")]
    pub channel: String,
    /// User Id
    #[serde(rename = "user")]
    pub user: String,
}

impl ChannelCompositeKey {
    /// Composite primary key consisting of channel and user id
    pub fn new(channel: String, user: String) -> ChannelCompositeKey {
        ChannelCompositeKey {
            channel,
            user,
        }
    }
}


