/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateWebhookBody {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "avatar", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Option<String>>,
}

impl CreateWebhookBody {
    pub fn new(name: String) -> CreateWebhookBody {
        CreateWebhookBody {
            name,
            avatar: None,
        }
    }
}


