/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateVoiceUserResponse {
    /// Token for authenticating with the voice server
    #[serde(rename = "token")]
    pub token: String,
}

impl CreateVoiceUserResponse {
    pub fn new(token: String) -> CreateVoiceUserResponse {
        CreateVoiceUserResponse {
            token,
        }
    }
}


