/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataPasswordReset {
    /// Reset token
    #[serde(rename = "token")]
    pub token: String,
    /// New password
    #[serde(rename = "password")]
    pub password: String,
    /// Whether to logout all sessions
    #[serde(rename = "remove_sessions", skip_serializing_if = "Option::is_none")]
    pub remove_sessions: Option<bool>,
}

impl DataPasswordReset {
    pub fn new(token: String, password: String) -> DataPasswordReset {
        DataPasswordReset {
            token,
            password,
            remove_sessions: None,
        }
    }
}


