/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// DataCreateEmojiParent : Parent information



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataCreateEmojiParent {
    #[serde(rename = "type")]
    pub r#type: RHashType,
    #[serde(rename = "id")]
    pub id: String,
}

impl DataCreateEmojiParent {
    /// Parent information
    pub fn new(r#type: RHashType, id: String) -> DataCreateEmojiParent {
        DataCreateEmojiParent {
            r#type,
            id,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "Detached")]
    Detached,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Detached
    }
}

