/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// DataEditUserStatus : New user status



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataEditUserStatus {
    /// Custom status text
    #[serde(rename = "text", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub text: Option<Option<String>>,
    #[serde(rename = "presence", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub presence: Option<Option<crate::models::Presence>>,
}

impl DataEditUserStatus {
    /// New user status
    pub fn new() -> DataEditUserStatus {
        DataEditUserStatus {
            text: None,
            presence: None,
        }
    }
}


