/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataSetServerDefaultPermission {
    /// Default member permission value
    #[serde(rename = "permissions")]
    pub permissions: i32,
}

impl DataSetServerDefaultPermission {
    pub fn new(permissions: i32) -> DataSetServerDefaultPermission {
        DataSetServerDefaultPermission {
            permissions,
        }
    }
}


