/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataCreateAccount {
    /// Valid email address
    #[serde(rename = "email")]
    pub email: String,
    /// Password
    #[serde(rename = "password")]
    pub password: String,
    /// Invite code
    #[serde(rename = "invite", skip_serializing_if = "Option::is_none")]
    pub invite: Option<String>,
    /// Captcha verification code
    #[serde(rename = "captcha", skip_serializing_if = "Option::is_none")]
    pub captcha: Option<String>,
}

impl DataCreateAccount {
    pub fn new(email: String, password: String) -> DataCreateAccount {
        DataCreateAccount {
            email,
            password,
            invite: None,
            captcha: None,
        }
    }
}


