/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataCreateServer {
    /// Server name
    #[serde(rename = "name")]
    pub name: String,
    /// Server description
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// Whether this server is age-restricted
    #[serde(rename = "nsfw", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nsfw: Option<Option<bool>>,
}

impl DataCreateServer {
    pub fn new(name: String) -> DataCreateServer {
        DataCreateServer {
            name,
            description: None,
            nsfw: None,
        }
    }
}


