/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataSendFriendRequest {
    #[serde(rename = "username")]
    pub username: String,
}

impl DataSendFriendRequest {
    pub fn new(username: String) -> DataSendFriendRequest {
        DataSendFriendRequest {
            username,
        }
    }
}


