/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataCreateBot {
    /// Bot username
    #[serde(rename = "name")]
    pub name: String,
}

impl DataCreateBot {
    pub fn new(name: String) -> DataCreateBot {
        DataCreateBot {
            name,
        }
    }
}


