/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataOnboard {
    /// New username which will be used to identify the user on the platform
    #[serde(rename = "username")]
    pub username: String,
}

impl DataOnboard {
    pub fn new(username: String) -> DataOnboard {
        DataOnboard {
            username,
        }
    }
}


