/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataCreateServer {
    /// Server name
    #[serde(rename = "name")]
    pub name: String,
    /// Server description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Whether this server is age-restricted
    #[serde(rename = "nsfw", skip_serializing_if = "Option::is_none")]
    pub nsfw: Option<bool>,
}

impl DataCreateServer {
    pub fn new(name: String) -> DataCreateServer {
        DataCreateServer {
            name,
            description: None,
            nsfw: None,
        }
    }
}


