/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataEditSession {
    /// Session friendly name
    #[serde(rename = "friendly_name")]
    pub friendly_name: String,
}

impl DataEditSession {
    pub fn new(friendly_name: String) -> DataEditSession {
        DataEditSession {
            friendly_name,
        }
    }
}


