/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// DataCreateStrike : New strike information



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataCreateStrike {
    /// Id of reported user
    #[serde(rename = "user_id")]
    pub user_id: String,
    /// Attached reason
    #[serde(rename = "reason")]
    pub reason: String,
}

impl DataCreateStrike {
    /// New strike information
    pub fn new(user_id: String, reason: String) -> DataCreateStrike {
        DataCreateStrike {
            user_id,
            reason,
        }
    }
}


