/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// DataMessageSendInteractions : Information about how this message should be interacted with



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataMessageSendInteractions {
    /// Reactions which should always appear and be distinct
    #[serde(rename = "reactions", skip_serializing_if = "Option::is_none")]
    pub reactions: Option<Vec<String>>,
    /// Whether reactions should be restricted to the given list
    #[serde(rename = "restrict_reactions", skip_serializing_if = "Option::is_none")]
    pub restrict_reactions: Option<bool>,
}

impl DataMessageSendInteractions {
    /// Information about how this message should be interacted with
    pub fn new() -> DataMessageSendInteractions {
        DataMessageSendInteractions {
            reactions: None,
            restrict_reactions: None,
        }
    }
}


