/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Data {
    #[serde(rename = "permissions")]
    pub permissions: Box<crate::models::DataPermissions>,
}

impl Data {
    pub fn new(permissions: crate::models::DataPermissions) -> Data {
        Data {
            permissions: Box::new(permissions),
        }
    }
}


