/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// DataMessageSendMasquerade : Masquerade to apply to this message



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataMessageSendMasquerade {
    /// Replace the display name shown on this message
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// Replace the avatar shown on this message (URL to image file)
    #[serde(rename = "avatar", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Option<String>>,
    /// Replace the display role colour shown on this message  Must have `ManageRole` permission to use
    #[serde(rename = "colour", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub colour: Option<Option<String>>,
}

impl DataMessageSendMasquerade {
    /// Masquerade to apply to this message
    pub fn new() -> DataMessageSendMasquerade {
        DataMessageSendMasquerade {
            name: None,
            avatar: None,
            colour: None,
        }
    }
}


