/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataDefaultChannelPermissionsAnyOf1 {
    /// Allow / deny values to set for members in this `TextChannel` or `VoiceChannel`
    #[serde(rename = "permissions")]
    pub permissions: Box<crate::models::Override>,
}

impl DataDefaultChannelPermissionsAnyOf1 {
    pub fn new(permissions: crate::models::Override) -> DataDefaultChannelPermissionsAnyOf1 {
        DataDefaultChannelPermissionsAnyOf1 {
            permissions: Box::new(permissions),
        }
    }
}


