/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// EmbedOneOf2 : Video



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmbedOneOf2 {
    #[serde(rename = "type")]
    pub r#type: RHashType,
    /// URL to the original video
    #[serde(rename = "url")]
    pub url: String,
    /// Width of the video
    #[serde(rename = "width")]
    pub width: i32,
    /// Height of the video
    #[serde(rename = "height")]
    pub height: i32,
}

impl EmbedOneOf2 {
    /// Video
    pub fn new(r#type: RHashType, url: String, width: i32, height: i32) -> EmbedOneOf2 {
        EmbedOneOf2 {
            r#type,
            url,
            width,
            height,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "Video")]
    Video,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Video
    }
}

