/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// EmbedOneOfImage : Embedded image



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmbedOneOfImage {
    /// URL to the original image
    #[serde(rename = "url")]
    pub url: String,
    /// Width of the image
    #[serde(rename = "width")]
    pub width: i32,
    /// Height of the image
    #[serde(rename = "height")]
    pub height: i32,
    #[serde(rename = "size")]
    pub size: crate::models::ImageSize,
}

impl EmbedOneOfImage {
    /// Embedded image
    pub fn new(url: String, width: i32, height: i32, size: crate::models::ImageSize) -> EmbedOneOfImage {
        EmbedOneOfImage {
            url,
            width,
            height,
            size,
        }
    }
}


