/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// EmojiParent : What owns this emoji



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmojiParent {
    #[serde(rename = "type")]
    pub _type: Type,
    #[serde(rename = "id")]
    pub id: String,
}

impl EmojiParent {
    /// What owns this emoji
    pub fn new(_type: Type, id: String) -> EmojiParent {
        EmojiParent {
            _type,
            id,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Detached")]
    Detached,
}

impl Default for Type {
    fn default() -> Type {
        Self::Detached
    }
}

