/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// EmojiParent : What owns this emoji



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmojiParent {
    #[serde(rename = "type")]
    pub r#type: RHashType,
    #[serde(rename = "id")]
    pub id: String,
}

impl EmojiParent {
    /// What owns this emoji
    pub fn new(r#type: RHashType, id: String) -> EmojiParent {
        EmojiParent {
            r#type,
            id,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "Detached")]
    Detached,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Detached
    }
}

