/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// ErrorOneOf : This error was not labeled :(



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErrorOneOf {
    #[serde(rename = "type")]
    pub _type: Type,
}

impl ErrorOneOf {
    /// This error was not labeled :(
    pub fn new(_type: Type) -> ErrorOneOf {
        ErrorOneOf {
            _type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "LabelMe")]
    LabelMe,
}

impl Default for Type {
    fn default() -> Type {
        Self::LabelMe
    }
}

