/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErrorOneOf10 {
    #[serde(rename = "type")]
    pub _type: Type,
}

impl ErrorOneOf10 {
    pub fn new(_type: Type) -> ErrorOneOf10 {
        ErrorOneOf10 {
            _type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "UnknownChannel")]
    UnknownChannel,
}

impl Default for Type {
    fn default() -> Type {
        Self::UnknownChannel
    }
}

