/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErrorOneOf31 {
    #[serde(rename = "type")]
    pub _type: Type,
    #[serde(rename = "permission")]
    pub permission: crate::models::Permission,
}

impl ErrorOneOf31 {
    pub fn new(_type: Type, permission: crate::models::Permission) -> ErrorOneOf31 {
        ErrorOneOf31 {
            _type,
            permission,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "MissingPermission")]
    MissingPermission,
}

impl Default for Type {
    fn default() -> Type {
        Self::MissingPermission
    }
}

