/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErrorOneOf32 {
    #[serde(rename = "type")]
    pub _type: Type,
    #[serde(rename = "permission")]
    pub permission: crate::models::UserPermission,
}

impl ErrorOneOf32 {
    pub fn new(_type: Type, permission: crate::models::UserPermission) -> ErrorOneOf32 {
        ErrorOneOf32 {
            _type,
            permission,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "MissingUserPermission")]
    MissingUserPermission,
}

impl Default for Type {
    fn default() -> Type {
        Self::MissingUserPermission
    }
}

