/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErrorOneOf20 {
    #[serde(rename = "type")]
    pub _type: Type,
    #[serde(rename = "max")]
    pub max: i32,
}

impl ErrorOneOf20 {
    pub fn new(_type: Type, max: i32) -> ErrorOneOf20 {
        ErrorOneOf20 {
            _type,
            max,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "GroupTooLarge")]
    GroupTooLarge,
}

impl Default for Type {
    fn default() -> Type {
        Self::GroupTooLarge
    }
}

