/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// Image : Image



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Image {
    /// URL to the original image
    #[serde(rename = "url")]
    pub url: String,
    /// Width of the image
    #[serde(rename = "width")]
    pub width: i32,
    /// Height of the image
    #[serde(rename = "height")]
    pub height: i32,
    /// Positioning and size
    #[serde(rename = "size")]
    pub size: Box<crate::models::ImageSize>,
}

impl Image {
    /// Image
    pub fn new(url: String, width: i32, height: i32, size: crate::models::ImageSize) -> Image {
        Image {
            url,
            width,
            height,
            size: Box::new(size),
        }
    }
}


