/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// IndexAccesses : Access information



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IndexAccesses {
    /// Operations since timestamp
    #[serde(rename = "ops")]
    pub ops: i32,
    /// ISO8601 formatted timestamp
    #[serde(rename = "since")]
    pub since: String,
}

impl IndexAccesses {
    /// Access information
    pub fn new(ops: i32, since: String) -> IndexAccesses {
        IndexAccesses {
            ops,
            since,
        }
    }
}


