/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InviteBotDestination {
    /// Server Id
    #[serde(rename = "server")]
    pub server: String,
    /// Group Id
    #[serde(rename = "group")]
    pub group: String,
}

impl InviteBotDestination {
    pub fn new(server: String, group: String) -> InviteBotDestination {
        InviteBotDestination {
            server,
            group,
        }
    }
}


