/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// LatencyHistogramEntry : Histogram entry



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LatencyHistogramEntry {
    /// Time
    #[serde(rename = "micros")]
    pub micros: i64,
    /// Count
    #[serde(rename = "count")]
    pub count: i64,
}

impl LatencyHistogramEntry {
    /// Histogram entry
    pub fn new(micros: i64, count: i64) -> LatencyHistogramEntry {
        LatencyHistogramEntry {
            micros,
            count,
        }
    }
}


