/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// MemberId : Unique member id



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MemberId {
    /// Server Id
    #[serde(rename = "server")]
    pub server: String,
    /// User Id
    #[serde(rename = "user")]
    pub user: String,
}

impl MemberId {
    /// Unique member id
    pub fn new(server: String, user: String) -> MemberId {
        MemberId {
            server,
            user,
        }
    }
}


