/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// Metadata : Metadata associated with file



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Metadata {
    #[serde(rename = "type")]
    pub _type: Type,
    #[serde(rename = "width")]
    pub width: i32,
    #[serde(rename = "height")]
    pub height: i32,
}

impl Metadata {
    /// Metadata associated with file
    pub fn new(_type: Type, width: i32, height: i32) -> Metadata {
        Metadata {
            _type,
            width,
            height,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Audio")]
    Audio,
}

impl Default for Type {
    fn default() -> Type {
        Self::Audio
    }
}

