/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// MetadataOneOf4 : File is audio



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetadataOneOf4 {
    #[serde(rename = "type")]
    pub _type: Type,
}

impl MetadataOneOf4 {
    /// File is audio
    pub fn new(_type: Type) -> MetadataOneOf4 {
        MetadataOneOf4 {
            _type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Audio")]
    Audio,
}

impl Default for Type {
    fn default() -> Type {
        Self::Audio
    }
}

