/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// MetadataOneOf : File is just a generic uncategorised file



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetadataOneOf {
    #[serde(rename = "type")]
    pub _type: Type,
}

impl MetadataOneOf {
    /// File is just a generic uncategorised file
    pub fn new(_type: Type) -> MetadataOneOf {
        MetadataOneOf {
            _type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "File")]
    File,
}

impl Default for Type {
    fn default() -> Type {
        Self::File
    }
}

