/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// MfaMethod : MFA method

/// MFA method
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MfaMethod {
    #[serde(rename = "Password")]
    Password,
    #[serde(rename = "Recovery")]
    Recovery,
    #[serde(rename = "Totp")]
    Totp,

}

impl ToString for MfaMethod {
    fn to_string(&self) -> String {
        match self {
            Self::Password => String::from("Password"),
            Self::Recovery => String::from("Recovery"),
            Self::Totp => String::from("Totp"),
        }
    }
}

impl Default for MfaMethod {
    fn default() -> MfaMethod {
        Self::Password
    }
}




