/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MfaResponseAnyOf {
    #[serde(rename = "password")]
    pub password: String,
}

impl MfaResponseAnyOf {
    pub fn new(password: String) -> MfaResponseAnyOf {
        MfaResponseAnyOf {
            password,
        }
    }
}


