/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OptionsQueryStale {
    /// Array of message IDs
    #[serde(rename = "ids")]
    pub ids: Vec<String>,
}

impl OptionsQueryStale {
    pub fn new(ids: Vec<String>) -> OptionsQueryStale {
        OptionsQueryStale {
            ids,
        }
    }
}


