/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OptionsFetchSettings {
    /// Keys to fetch
    #[serde(rename = "keys")]
    pub keys: Vec<String>,
}

impl OptionsFetchSettings {
    pub fn new(keys: Vec<String>) -> OptionsFetchSettings {
        OptionsFetchSettings {
            keys,
        }
    }
}


