/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// OverrideField : Representation of a single permission override as it appears on models and in the database



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OverrideField {
    /// Allow bit flags
    #[serde(rename = "a")]
    pub a: i64,
    /// Disallow bit flags
    #[serde(rename = "d")]
    pub d: i64,
}

impl OverrideField {
    /// Representation of a single permission override as it appears on models and in the database
    pub fn new(a: i64, d: i64) -> OverrideField {
        OverrideField {
            a,
            d,
        }
    }
}


