/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// OwnedBotsResponse : Both lists are sorted by their IDs.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OwnedBotsResponse {
    /// Bot objects
    #[serde(rename = "bots")]
    pub bots: Vec<crate::models::Bot>,
    /// User objects
    #[serde(rename = "users")]
    pub users: Vec<crate::models::User>,
}

impl OwnedBotsResponse {
    /// Both lists are sorted by their IDs.
    pub fn new(bots: Vec<crate::models::Bot>, users: Vec<crate::models::User>) -> OwnedBotsResponse {
        OwnedBotsResponse {
            bots,
            users,
        }
    }
}


