/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// PublicBot : Public Bot



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PublicBot {
    /// Bot Id
    #[serde(rename = "_id")]
    pub _id: String,
    /// Bot Username
    #[serde(rename = "username")]
    pub username: String,
    /// Profile Avatar
    #[serde(rename = "avatar")]
    pub avatar: String,
    /// Profile Description
    #[serde(rename = "description")]
    pub description: String,
}

impl PublicBot {
    /// Public Bot
    pub fn new(_id: String, username: String, avatar: String, description: String) -> PublicBot {
        PublicBot {
            _id,
            username,
            avatar,
            description,
        }
    }
}


