/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PublicBot {
    /// Bot Id
    #[serde(rename = "_id")]
    pub _id: String,
    /// Bot Username
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "avatar", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Box<crate::models::PublicBotAvatar>>,
    /// Profile Description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl PublicBot {
    pub fn new(_id: String, username: String) -> PublicBot {
        PublicBot {
            _id,
            username,
            avatar: None,
            description: None,
        }
    }
}


