/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RAuthError {
    #[serde(rename = "type")]
    pub _type: Type,
    #[serde(rename = "with")]
    pub with: String,
    #[serde(rename = "operation")]
    pub operation: String,
}

impl RAuthError {
    pub fn new(_type: Type, with: String, operation: String) -> RAuthError {
        RAuthError {
            _type,
            with,
            operation,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "DisallowedMFAMethod")]
    DisallowedMFAMethod,
}

impl Default for Type {
    fn default() -> Type {
        Self::DisallowedMFAMethod
    }
}

