/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// Reply : Representation of a message reply before it is sent.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Reply {
    /// Message Id
    #[serde(rename = "id")]
    pub id: String,
    /// Whether this reply should mention the message's author
    #[serde(rename = "mention")]
    pub mention: bool,
}

impl Reply {
    /// Representation of a message reply before it is sent.
    pub fn new(id: String, mention: bool) -> Reply {
        Reply {
            id,
            mention,
        }
    }
}


