/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// ReportedContentOneOf : Report a message



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReportedContentOneOf {
    #[serde(rename = "type")]
    pub r#type: RHashType,
    /// ID of the message
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "report_reason")]
    pub report_reason: crate::models::ContentReportReason,
}

impl ReportedContentOneOf {
    /// Report a message
    pub fn new(r#type: RHashType, id: String, report_reason: crate::models::ContentReportReason) -> ReportedContentOneOf {
        ReportedContentOneOf {
            r#type,
            id,
            report_reason,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "Message")]
    Message,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Message
    }
}

