/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResponseVerify {
    #[serde(rename = "ticket")]
    pub ticket: Box<crate::models::ResponseVerifyAnyOfTicket>,
}

impl ResponseVerify {
    pub fn new(ticket: crate::models::ResponseVerifyAnyOfTicket) -> ResponseVerify {
        ResponseVerify {
            ticket: Box::new(ticket),
        }
    }
}


