/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// ResponseLoginOneOfSubscription : Web Push subscription



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ResponseLoginOneOfSubscription {
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    #[serde(rename = "p256dh")]
    pub p256dh: String,
    #[serde(rename = "auth")]
    pub auth: String,
}

impl ResponseLoginOneOfSubscription {
    /// Web Push subscription
    pub fn new(endpoint: String, p256dh: String, auth: String) -> ResponseLoginOneOfSubscription {
        ResponseLoginOneOfSubscription {
            endpoint,
            p256dh,
            auth,
        }
    }
}


