/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// RevoltFeaturesAutumn : File server service configuration



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RevoltFeaturesAutumn {
    /// Whether the service is enabled
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// URL pointing to the service
    #[serde(rename = "url")]
    pub url: String,
}

impl RevoltFeaturesAutumn {
    /// File server service configuration
    pub fn new(enabled: bool, url: String) -> RevoltFeaturesAutumn {
        RevoltFeaturesAutumn {
            enabled,
            url,
        }
    }
}


