/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// SpecialOneOf6 : Soundcloud track



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpecialOneOf6 {
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl SpecialOneOf6 {
    /// Soundcloud track
    pub fn new(r#type: RHashType) -> SpecialOneOf6 {
        SpecialOneOf6 {
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "Soundcloud")]
    Soundcloud,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Soundcloud
    }
}

