/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// SpecialOneOf4 : Twitch stream or clip



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpecialOneOf4 {
    #[serde(rename = "type")]
    pub _type: Type,
    #[serde(rename = "content_type")]
    pub content_type: crate::models::TwitchType,
    #[serde(rename = "id")]
    pub id: String,
}

impl SpecialOneOf4 {
    /// Twitch stream or clip
    pub fn new(_type: Type, content_type: crate::models::TwitchType, id: String) -> SpecialOneOf4 {
        SpecialOneOf4 {
            _type,
            content_type,
            id,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Twitch")]
    Twitch,
}

impl Default for Type {
    fn default() -> Type {
        Self::Twitch
    }
}

