/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// SpecialOneOf1 : Content hint that this contains a GIF  Use metadata to find video or image to play



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpecialOneOf1 {
    #[serde(rename = "type")]
    pub _type: Type,
}

impl SpecialOneOf1 {
    /// Content hint that this contains a GIF  Use metadata to find video or image to play
    pub fn new(_type: Type) -> SpecialOneOf1 {
        SpecialOneOf1 {
            _type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "GIF")]
    GIF,
}

impl Default for Type {
    fn default() -> Type {
        Self::GIF
    }
}

