/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// SpecialOneOf6 : Soundcloud track



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpecialOneOf6 {
    #[serde(rename = "type")]
    pub _type: Type,
}

impl SpecialOneOf6 {
    /// Soundcloud track
    pub fn new(_type: Type) -> SpecialOneOf6 {
        SpecialOneOf6 {
            _type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Soundcloud")]
    Soundcloud,
}

impl Default for Type {
    fn default() -> Type {
        Self::Soundcloud
    }
}

