/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// SpecialOneOf : No remote content



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpecialOneOf {
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl SpecialOneOf {
    /// No remote content
    pub fn new(r#type: RHashType) -> SpecialOneOf {
        SpecialOneOf {
            r#type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "None")]
    None,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::None
    }
}

