/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// Special : Information about special remote content



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Special {
    #[serde(rename = "type")]
    pub _type: Type,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(rename = "content_type")]
    pub content_type: crate::models::BandcampType,
}

impl Special {
    /// Information about special remote content
    pub fn new(_type: Type, id: String, content_type: crate::models::BandcampType) -> Special {
        Special {
            _type,
            id,
            timestamp: None,
            content_type,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Bandcamp")]
    Bandcamp,
}

impl Default for Type {
    fn default() -> Type {
        Self::Bandcamp
    }
}

