/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SystemMessageOneOf7 {
    #[serde(rename = "type")]
    pub r#type: RHashType,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "by")]
    pub by: String,
}

impl SystemMessageOneOf7 {
    pub fn new(r#type: RHashType, name: String, by: String) -> SystemMessageOneOf7 {
        SystemMessageOneOf7 {
            r#type,
            name,
            by,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "channel_renamed")]
    ChannelRenamed,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::ChannelRenamed
    }
}

