/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.6.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SystemMessageOneOf {
    #[serde(rename = "type")]
    pub r#type: RHashType,
    #[serde(rename = "content")]
    pub content: String,
}

impl SystemMessageOneOf {
    pub fn new(r#type: RHashType, content: String) -> SystemMessageOneOf {
        SystemMessageOneOf {
            r#type,
            content,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "text")]
    Text,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Text
    }
}

