/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SystemMessageOneOf5 {
    #[serde(rename = "type")]
    pub _type: Type,
    #[serde(rename = "id")]
    pub id: String,
}

impl SystemMessageOneOf5 {
    pub fn new(_type: Type, id: String) -> SystemMessageOneOf5 {
        SystemMessageOneOf5 {
            _type,
            id,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "user_kicked")]
    UserKicked,
}

impl Default for Type {
    fn default() -> Type {
        Self::UserKicked
    }
}

