/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SystemMessageOneOf1 {
    #[serde(rename = "type")]
    pub _type: Type,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "by")]
    pub by: String,
}

impl SystemMessageOneOf1 {
    pub fn new(_type: Type, id: String, by: String) -> SystemMessageOneOf1 {
        SystemMessageOneOf1 {
            _type,
            id,
            by,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "user_added")]
    UserAdded,
}

impl Default for Type {
    fn default() -> Type {
        Self::UserAdded
    }
}

