/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */

/// Video : Video



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Video {
    /// URL to the original video
    #[serde(rename = "url")]
    pub url: String,
    /// Width of the video
    #[serde(rename = "width")]
    pub width: i32,
    /// Height of the video
    #[serde(rename = "height")]
    pub height: i32,
}

impl Video {
    /// Video
    pub fn new(url: String, width: i32, height: i32) -> Video {
        Video {
            url,
            width,
            height,
        }
    }
}


