/*
 * Revolt API
 *
 * Open source user-first chat platform.
 *
 * The version of the OpenAPI document: 0.5.5
 * Contact: contact@revolt.chat
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VoiceFeature {
    /// Whether voice is enabled
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// URL pointing to the voice API
    #[serde(rename = "url")]
    pub url: String,
    /// URL pointing to the voice WebSocket server
    #[serde(rename = "ws")]
    pub ws: String,
}

impl VoiceFeature {
    pub fn new(enabled: bool, url: String, ws: String) -> VoiceFeature {
        VoiceFeature {
            enabled,
            url,
            ws,
        }
    }
}


