name: Rust

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: cargo test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@nightly
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
